library(shiny)
library(shinydashboard)
library(plotly)
library(ggplot2)
suppressPackageStartupMessages(library(googleVis))
library(readr)
library(tidyverse)
library(lubridate)
library(splitstackshape)
library(stringi)
library(googleVis)
library(googleway)
library(data.table)
library(DT)
gun <- as.tibble(data.table::fread(str_c("gun-violence-data_01-2013_03-2018.csv"),header=TRUE,stringsAsFactors = FALSE, na.strings=c("NA", "")))
gun$date <- as.Date(gun$date, format = "%m/%d/%Y")
gun$year <- year(gun$date)
gun$Victims = gun$n_killed + gun$n_injured
gun1 <- gun %>% select(Victims,n_killed,n_injured)
choices <- colnames(gun1)
statepop <- read.csv('states_population.csv')
statepop <- statepop %>% rename(., state = states)
incident <- gun %>% group_by(state) %>% summarize(stateIncidents=n())
incident <-left_join(statepop, incident, by="state")
incident$population <- as.character(incident$population)
incident$population <- gsub(',','',incident$population)
incident$population <- as.integer(incident$population)
incident$per100000 <- round((incident$stateIncidents / incident$population) * 100000)
class(incident$per100000)
class(incident$stateIncidents)
incident$per100000 <- as.integer((incident$per100000))
class(incident$per100000)
class(incident$stateIncidents)
length(incident$stateIncidents)
nrow(incident)
ncol(incident)
citiespop <- read.csv('cities_population.csv')
gun <- gun %>% mutate(cities = city_or_county)
city <- gun %>% group_by(cities) %>% summarize(cityIncidents=n())
city <- left_join(citiespop, city, by="cities")
city$population <- as.character(city$population)
city$population<- gsub(',','',city$population)
city$population <- as.integer((city$population))
city$per100000 <- round((city$cityIncidents/city$population)* 100000)
city = city %>% filter(population > 600000)
incident <- incident %>% filter(state != 'District of Columbia')
city <- city %>% filter(cities != 'Washington')
city <- city %>% mutate(cityIncidents = log(cityIncidents)) %>% arrange(desc(cityIncidents))
city <- city %>% arrange(desc(per100000))
gun$incident_characteristics <- gsub("\\|\\|", "|", gun$incident_characteristics)
IncCharac <- splitstackshape::cSplit(gun, 'incident_characteristics', sep =  '|', direction="long")
Dead <- c("Shot - Dead (murder, accidental, suicide)", "Accidental Shooting - Death", "Murder/Suicide", "Mass Murder (4+ deceased victims excluding the subject/suspect/perpetrator , one location)", "Suicide^", "Attempted Murder/Suicide (one variable unsuccessful)")
Involvement <- c("Terrorism Involvement", "Drug involvement", "Gang involvement")
Values <- IncCharac %>% filter(incident_characteristics %in% Dead | incident_characteristics %in% Involvement)
Values <- left_join(Values, gun %>% select(incident_id, longitude, latitude, location_description, Victims), by="incident_id")
#incident = top_n(incident[order(incident$stateIncidents),],20, stateIncidents)
#incident = incident[order(incident$per100000,incident$stateIncidents),]
city = na.omit(city)
city = city %>% mutate(., cityIncidents = round(cityIncidents,3), per100000 = round(per100000,3))
incident1 = incident %>% select(stateIncidents,per100000)
choices1 <- colnames(incident1)
j =incident %>% select(stateIncidents,state) %>% top_n(20,stateIncidents)
k= incident %>% select(per100000,state) %>% top_n(20,per100000)
z <-inner_join(j,k,by='state')
incident2= city%>%select(cityIncidents,per100000)
incident2 = round(incident2,2)
choices2<- colnames(incident2)
h=city %>% select(cityIncidents,cities)%>%top_n(20,cityIncidents)
l= city %>% select(per100000,cities) %>% top_n(20,per100000)
d <-inner_join(h,l,by='cities')
address <- inner_join(city,gun,by="cities")
address <-address %>% select(-population,-incident_id,-date,-state,-city_or_county,-address,-n_killed,-n_injured,-incident_url,-source_url,-incident_url_fields_missing,-congressional_district,-gun_stolen,-gun_type,-incident_characteristics,-location_description,-n_guns_involved,-notes,-participant_age,-participant_age_group,-participant_gender,-participant_name)
address <- address %>% select(-participant_relationship,-participant_status,-participant_type,-sources,-state_house_district,-state_senate_district,-year,-Victims)
address <- address %>% group_by(cities)
address <- unique(address)
